import { environment } from "../common/environments/environment";

// src/environments/environment.ts
export const environmentEntries = {
    production: false,
    apiUrl: environment.services.usersAndAddresses,
    movementsApi: environment.services.accesses,
    endpoints: {
        // Endpoints existentes
        users: '/users/getall',
        movements: '/movements_entryToNeighbor',
        userByDni: '/userAllowedByDni',
        addVehicle: '/addVehicleToUser',
        logicDown: '/logicDown',
        visitorQr: '/visitor-qr/image',
        ownersAndTenants: '/user_Allowed/ownersAndTenants',
        visitorsByOwner: '/user_Allowed/visitors/by',
        updateVisitor: '/user_Allowed/visitor/update',
        vehicleTypes: '/getAll/vehiclesType',
        validateQr: '/visitor-qr',
        generateQr: '/visitor-qr/generate',
        usersType: '/users_Type',
        giveTempRange: '/user_Allowed/giveTempRange',
        usersAllowedWithoutMovements: '/user_Allowed/getAllUsersAllowed/WithAuthRangeWithoutMovements',
        usersAllowed: '/user_Allowed/getAllUsersAllowed',
        movementsEntry: '/movements_entry/register',
        movementsExit: '/movements_exit/register',
        emergencyEntry: '/emergency/register_entry',
        emergencyExit: '/emergency/register_exit',
        ownerRenterEntry: '/movements_entry/register',
        ownerRenterList: '/user_Allowed/ownersAndTenants/',
        ownerExit: '/movements_exit/registerOwnerExit',
        registerEmpSuppEntry: '/movements_entry/registerEmpSupp',
        registerEmpSuppExit: '/movements_exit/registerEmpSupp',
        getSuppliesAndEmployers: '/GetSuppliesAndEmployeers',
        getAuthRangeByDoc: '/GetAuthRangeByDoc',
        registerEntryEmployeers: '/attendances/post',
        registerExitEmployeers: '/attendances/putArrivalTime',
        //////// Endpoints de métricas
        dailyAccess: '/daily-access-count',
        dailyExit: '/daily-exit-count',
        accessCountByUserTypeFilter: '/access-count-by-user-type-filter',
        exitCountByUserTypeFilter: '/exit-count-by-user-type-filter',
        totalAccessAndExitCounts: '/total-access-and-exit-counts',
        accessExitCountByDayFilter: '/access-exit-count-by-day-filter',
        dayWithMostAccesses: '/day-with-most-accesses',
        dayWithMostExits: '/day-with-most-exits',
        monthlyAccessCount: '/this-monthly-access-count',
        monthlyExitCount: '/this-monthly-exit-count',
        totalEntriesThisYear: '/total-entries-this-year',
        monthWithMostEntries: '/month-with-most-entries',
        totalExitsCurrentYear: '/total-exits-current-year',
        monthWithMostExits: '/month-with-most-exits',
        topUsersEntriesExits: '/top-users-entries-exits',
        guardWithMostExits: '/guard-with-most-exits',
        guardWithMostEntries: '/guard-with-most-entries',
        neighborWithMostInvitations: '/neighbor-with-most-invitations'
    }
};

export const API_ENDPOINTS = {
    // Endpoints que usan apiUrl
    USERS: `${environmentEntries.apiUrl}${environmentEntries.endpoints.users}`,
    
    // Endpoints que usan movementsApi
    MOVEMENTS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.movements}`,
    USER_BY_DNI: `${environmentEntries.movementsApi}${environmentEntries.endpoints.userByDni}`,
    ADD_VEHICLE: `${environmentEntries.movementsApi}${environmentEntries.endpoints.addVehicle}`,
    LOGIC_DOWN: `${environmentEntries.movementsApi}${environmentEntries.endpoints.logicDown}`,
    VISITOR_QR: `${environmentEntries.movementsApi}${environmentEntries.endpoints.visitorQr}`,
    VALIDATE_QR: `${environmentEntries.movementsApi}${environmentEntries.endpoints.validateQr}`,
    GENERATE_QR: `${environmentEntries.movementsApi}${environmentEntries.endpoints.generateQr}`,
    OWNERS_AND_TENANTS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.ownersAndTenants}`,
    VISITORS_BY_OWNER: `${environmentEntries.movementsApi}${environmentEntries.endpoints.visitorsByOwner}`,
    UPDATE_VISITOR: `${environmentEntries.movementsApi}${environmentEntries.endpoints.updateVisitor}`,
    VEHICLE_TYPES: `${environmentEntries.movementsApi}${environmentEntries.endpoints.vehicleTypes}`,
    USERS_TYPE: `${environmentEntries.movementsApi}${environmentEntries.endpoints.usersType}`,
    GIVE_TEMP_RANGE: `${environmentEntries.movementsApi}${environmentEntries.endpoints.giveTempRange}`,
    USERS_ALLOWED_WITHOUT_MOVEMENTS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.usersAllowedWithoutMovements}`,
    USERS_ALLOWED: `${environmentEntries.movementsApi}${environmentEntries.endpoints.usersAllowed}`,
    MOVEMENTS_ENTRY: `${environmentEntries.movementsApi}${environmentEntries.endpoints.movementsEntry}`,
    MOVEMENTS_EXIT: `${environmentEntries.movementsApi}${environmentEntries.endpoints.movementsExit}`,
    EMERGENCY_ENTRY: `${environmentEntries.movementsApi}${environmentEntries.endpoints.emergencyEntry}`,
    EMERGENCY_EXIT: `${environmentEntries.movementsApi}${environmentEntries.endpoints.emergencyExit}`,
    OWNER_RENTER_ENTRY: `${environmentEntries.movementsApi}${environmentEntries.endpoints.ownerRenterEntry}`,
    OWNER_RENTER_LIST: `${environmentEntries.movementsApi}${environmentEntries.endpoints.ownerRenterList}`,
    OWNER_EXIT: `${environmentEntries.movementsApi}${environmentEntries.endpoints.ownerExit}`,
    REGISTER_EMP_SUPP_ENTRY: `${environmentEntries.movementsApi}${environmentEntries.endpoints.registerEmpSuppEntry}`,
    REGISTER_EMP_SUPP_EXIT: `${environmentEntries.movementsApi}${environmentEntries.endpoints.registerEmpSuppExit}`,
    GET_SUPPLIES_AND_EMPLOYERS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.getSuppliesAndEmployers}`,
    GET_AUTH_RANGE_BY_DOC: `${environmentEntries.movementsApi}${environmentEntries.endpoints.getAuthRangeByDoc}`,
    REGISTER_ENTRY_EMPLOYEERS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.registerEntryEmployeers}`,
    REGISTER_EXIT_EMPLOYEERS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.registerExitEmployeers}`,
    // Endpoints de métricas
    DAILY_ACCESS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.dailyAccess}`,
    DAILY_EXIT: `${environmentEntries.movementsApi}${environmentEntries.endpoints.dailyExit}`,
    ACCESS_COUNT_USER_TYPE_FILTER: `${environmentEntries.movementsApi}${environmentEntries.endpoints.accessCountByUserTypeFilter}`,
    EXIT_COUNT_USER_TYPE_FILTER: `${environmentEntries.movementsApi}${environmentEntries.endpoints.exitCountByUserTypeFilter}`,
    TOTAL_ACCESS_AND_EXIT_COUNTS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.totalAccessAndExitCounts}`,
    ACCESS_EXIT_COUNT_BY_DAY_FILTER: `${environmentEntries.movementsApi}${environmentEntries.endpoints.accessExitCountByDayFilter}`,
    DAY_WITH_MOST_ACCESSES: `${environmentEntries.movementsApi}${environmentEntries.endpoints.dayWithMostAccesses}`,
    DAY_WITH_MOST_EXITS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.dayWithMostExits}`,
    MONTHLY_ACCESS_COUNT: `${environmentEntries.movementsApi}${environmentEntries.endpoints.monthlyAccessCount}`,
    MONTHLY_EXIT_COUNT: `${environmentEntries.movementsApi}${environmentEntries.endpoints.monthlyExitCount}`,
    TOTAL_ENTRIES_THIS_YEAR: `${environmentEntries.movementsApi}${environmentEntries.endpoints.totalEntriesThisYear}`,
    MONTH_WITH_MOST_ENTRIES: `${environmentEntries.movementsApi}${environmentEntries.endpoints.monthWithMostEntries}`,
    TOTAL_EXITS_CURRENT_YEAR: `${environmentEntries.movementsApi}${environmentEntries.endpoints.totalExitsCurrentYear}`,
    MONTH_WITH_MOST_EXITS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.monthWithMostExits}`,
    TOP_USERS_ENTRIES_EXITS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.topUsersEntriesExits}`,
    GUARD_WITH_MOST_EXITS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.guardWithMostExits}`,
    GUARD_WITH_MOST_ENTRIES: `${environmentEntries.movementsApi}${environmentEntries.endpoints.guardWithMostEntries}`,
    NEIGHBOR_WITH_MOST_INVITATIONS: `${environmentEntries.movementsApi}${environmentEntries.endpoints.neighborWithMostInvitations}`
};